import * as fs from 'fs';
import { isBuildEnvKey } from './build-config';
import { ENV_FIELDS, type EnvFieldDef } from './env-schema';
import { ensureProgramDataDir, programDataConfigPath, resolveConfigPath } from './paths';

export type EnvMap = Record<string, string>;

function parseLine(line: string): [string, string] | null {
  const t = line.trim();
  if (!t || t.startsWith('#')) return null;
  const eq = t.indexOf('=');
  if (eq <= 0) return null;
  const key = t.slice(0, eq).trim();
  let val = t.slice(eq + 1).trim();
  if (
    (val.startsWith('"') && val.endsWith('"')) ||
    (val.startsWith("'") && val.endsWith("'"))
  ) {
    val = val.slice(1, -1);
  }
  return [key, val];
}

export function readEnvFile(filePath?: string): EnvMap {
  const p = filePath ?? resolveConfigPath();
  const out: EnvMap = {};
  for (const f of ENV_FIELDS) {
    if (f.default !== undefined) out[f.key] = f.default;
  }
  if (!fs.existsSync(p)) return out;
  const text = fs.readFileSync(p, 'utf8');
  for (const line of text.split(/\r?\n/)) {
    const parsed = parseLine(line);
    if (parsed && !isBuildEnvKey(parsed[0])) out[parsed[0]] = parsed[1];
  }
  return out;
}

export function serializeEnvFile(values: EnvMap): string {
  const lines: string[] = [
    '# StationHub Agent — generated by desktop control panel',
    `# ${new Date().toISOString()}`,
    '',
  ];
  const written = new Set<string>();
  for (const f of ENV_FIELDS) {
    if (isBuildEnvKey(f.key)) continue;
    const v = values[f.key];
    if (v === undefined || v === '') continue;
    lines.push(`${f.key}=${v}`);
    written.add(f.key);
  }
  for (const [k, v] of Object.entries(values)) {
    if (written.has(k) || v === '' || isBuildEnvKey(k)) continue;
    lines.push(`${k}=${v}`);
  }
  lines.push('');
  return lines.join('\n');
}

export interface ValidateResult {
  ok: boolean;
  errors: string[];
}

export function validateEnv(values: EnvMap): ValidateResult {
  const errors: string[] = [];
  for (const f of ENV_FIELDS) {
    if (!f.required) continue;
    const v = values[f.key]?.trim();
    if (!v) errors.push(`${f.label} (${f.key}) là bắt buộc`);
  }
  return { ok: errors.length === 0, errors };
}

/** Ghi config production (ProgramData). */
export function writeConfigFile(
  values: EnvMap,
  targetPath?: string,
): string {
  const validation = validateEnv(values);
  if (!validation.ok) {
    throw new Error(validation.errors.join('\n'));
  }
  ensureProgramDataDir();
  const p = targetPath ?? programDataConfigPath();
  fs.writeFileSync(p, serializeEnvFile(values), 'utf8');
  return p;
}

export function fieldDefsByGroup(): Map<string, EnvFieldDef[]> {
  const m = new Map<string, EnvFieldDef[]>();
  for (const f of ENV_FIELDS) {
    const list = m.get(f.group) ?? [];
    list.push(f);
    m.set(f.group, list);
  }
  return m;
}
