import * as fs from 'fs';
import { isBuildEnvKey } from './build-config';
import { ENV_FIELDS, type EnvFieldDef } from './env-schema';
import { ensureProgramDataDir, programDataConfigPath, resolveConfigPath } from './paths';

export type EnvMap = Record<string, string>;

function unescapeEnvValue(value: string): string {
  let out = '';
  for (let i = 0; i < value.length; i++) {
    const ch = value[i];
    if (ch === '\\' && i + 1 < value.length) {
      const next = value[i + 1];
      if (next === '\\') {
        out += '\\';
        i++;
      } else if (next === '"') {
        out += '"';
        i++;
      } else if (next === 'n') {
        out += '\n';
        i++;
      } else if (next === 'r') {
        out += '\r';
        i++;
      } else if (next === 't') {
        out += '\t';
        i++;
      } else {
        out += next;
        i++;
      }
    } else {
      out += ch;
    }
  }
  return out;
}

/** Gộp backslash thừa do escape lặp (vd. C:\\\\\\\\ProgramData → C:\ProgramData). */
function collapseBackslashes(segment: string): string {
  return segment.replace(/\\+/g, '\\');
}

/** Chuẩn hóa đường dẫn Windows khi đọc/ghi agent.env */
function normalizeWindowsPath(value: string): string {
  let trimmed = value.trim();
  if (!trimmed) return trimmed;

  if (trimmed.length >= 2 && trimmed[1] === ':') {
    const rest = collapseBackslashes(trimmed.slice(2).replace(/\//g, '\\'));
    return `${trimmed[0]}:${rest}`;
  }

  return collapseBackslashes(trimmed.replace(/\//g, '\\'));
}

function isPathEnvKey(key: string): boolean {
  return (
    key.endsWith('_PATH') ||
    key.endsWith('_DIR') ||
    key.includes('PROFILE') ||
    key === 'CLOAK_RUNNER_SCRIPT'
  );
}

function normalizeEnvValue(key: string, value: string): string {
  if (!isPathEnvKey(key)) return value;
  return normalizeWindowsPath(value);
}

function parseLine(line: string): [string, string] | null {
  const t = line.trim();
  if (!t || t.startsWith('#')) return null;
  const eq = t.indexOf('=');
  if (eq <= 0) return null;
  const key = t.slice(0, eq).trim();
  let val = t.slice(eq + 1).trim();
  if (
    (val.startsWith('"') && val.endsWith('"')) ||
    (val.startsWith("'") && val.endsWith("'"))
  ) {
    val = unescapeEnvValue(val.slice(1, -1));
  }
  return [key, normalizeEnvValue(key, val)];
}

export function readEnvFile(filePath?: string): EnvMap {
  const p = filePath ?? resolveConfigPath();
  const out: EnvMap = {};
  for (const f of ENV_FIELDS) {
    if (f.default !== undefined) out[f.key] = f.default;
  }
  if (!fs.existsSync(p)) return out;
  const text = fs.readFileSync(p, 'utf8');
  for (const line of text.split(/\r?\n/)) {
    const parsed = parseLine(line);
    if (parsed && !isBuildEnvKey(parsed[0])) out[parsed[0]] = parsed[1];
  }
  return out;
}

function formatEnvValue(value: string): string {
  const v = value.trim();
  if (!/[\s#="'\\]/.test(v)) {
    return v;
  }
  return `"${v.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function normalizeEnvMap(values: EnvMap): EnvMap {
  const out: EnvMap = {};
  for (const [k, v] of Object.entries(values)) {
    if (v === undefined || v === '') continue;
    out[k] = normalizeEnvValue(k, v);
  }
  return out;
}

export function serializeEnvFile(values: EnvMap): string {
  const normalized = normalizeEnvMap(values);
  const lines: string[] = [
    '# StationHub Agent — generated by desktop control panel',
    `# ${new Date().toISOString()}`,
    '',
  ];
  const written = new Set<string>();
  for (const f of ENV_FIELDS) {
    if (isBuildEnvKey(f.key)) continue;
    const v = normalized[f.key];
    if (v === undefined || v === '') continue;
    lines.push(`${f.key}=${formatEnvValue(v)}`);
    written.add(f.key);
  }
  for (const [k, v] of Object.entries(normalized)) {
    if (written.has(k) || v === '' || isBuildEnvKey(k)) continue;
    lines.push(`${k}=${formatEnvValue(v)}`);
  }
  lines.push('');
  return lines.join('\n');
}

export interface ValidateResult {
  ok: boolean;
  errors: string[];
}

export function validateEnv(values: EnvMap): ValidateResult {
  const errors: string[] = [];
  for (const f of ENV_FIELDS) {
    if (!f.required) continue;
    const v = values[f.key]?.trim();
    if (!v) errors.push(`${f.label} (${f.key}) là bắt buộc`);
  }
  return { ok: errors.length === 0, errors };
}

/** Ghi config production (ProgramData). */
export function writeConfigFile(
  values: EnvMap,
  targetPath?: string,
): string {
  const validation = validateEnv(values);
  if (!validation.ok) {
    throw new Error(validation.errors.join('\n'));
  }
  ensureProgramDataDir();
  const p = targetPath ?? programDataConfigPath();
  const normalized = normalizeEnvMap(values);
  fs.writeFileSync(p, serializeEnvFile(normalized), 'utf8');
  return p;
}

export function fieldDefsByGroup(): Map<string, EnvFieldDef[]> {
  const m = new Map<string, EnvFieldDef[]>();
  for (const f of ENV_FIELDS) {
    const list = m.get(f.group) ?? [];
    list.push(f);
    m.set(f.group, list);
  }
  return m;
}
